-- =============================================
-- MIGRATION 006: UPDATE STUDENTS LIST
-- Replace all existing students with new list from Excel
-- =============================================

-- Clear existing data
DELETE FROM students;

-- Insert new students
INSERT INTO students (name, group_id, is_active) VALUES
  ('Quốc Vỹ', 'nhom_3', true),
  ('Tâm Anh', 'nhom_3', true),
  ('Kiến Văn', 'nhom_3', true),
  ('Phương Thảo', 'nhom_3', true),
  ('Uyên Nhi', 'nhom_1', true),
  ('Minh Lâm', 'nhom_1', true),
  ('Phước Lộc', 'nhom_1', true),
  ('Gia Bảo', 'nhom_1', true),
  ('Gia Bảo', 'nhom_1', true),
  ('Quốc Bảo', 'nhom_1', true),
  ('Bảo Ngọc', 'nhom_1', true),
  ('Gia Phú', 'nhom_1', true),
  ('Quang Đạo', 'nhom_1', true),
  ('Đức Anh', 'nhom_1', true),
  ('Minh Hiếu', 'nhom_1', true),
  ('Đức Huy', 'nhom_1', true),
  ('Giao Linh', 'nhom_1', true),
  ('Linh San', 'nhom_1', true),
  ('Công Giáp', 'nhom_1', true),
  ('Minh Hà', 'nhom_1', true),
  ('Minh Khang', 'nhom_3', true),
  ('Bảo Linh', 'nhom_2', true),
  ('Minh Nhật', 'nhom_2', true),
  ('Giang Sang', 'nhom_1', true),
  ('Phúc Thiện', 'nhom_2', true),
  ('Bảo Trân', 'nhom_2', true),
  ('Bảo An', 'nhom_2', true),
  ('An Khang', 'nhom_2', true),
  ('Minh Hoàng', 'nhom_2', true),
  ('Đức Danh', 'nhom_2', true),
  ('Tiểu Vy', 'nhom_2', true),
  ('Đăng Khoa', 'nhom_3', true),
  ('Thảo Nguyên', 'nhom_1', true),
  ('Phúc Thiên', 'nhom_3', true),
  ('Đăng Khoa', 'nhom_3', true),
  ('Nguyên Khôi', 'nhom_3', true),
  ('Minh Toàn', 'nhom_2', true),
  ('Hải Đăng', 'nhom_3', true),
  ('Đăng Duy', 'nhom_3', true),
  ('Thanh Ngọc', 'nhom_2', true),
  ('Bảo Ngọc', 'nhom_2', true),
  ('Nam Hải', 'nhom_2', true),
  ('Chu Minh Hoàng', 'nhom_1', true),
  ('Phi Anh', 'nhom_1', true),
  ('Nguyên Khôi (a)', 'nhom_3', true),
  ('Kim Điền', 'nhom_3', true),
  ('Nguyên Khang', 'nhom_2', true),
  ('Kim Khánh', 'nhom_3', true),
  ('Minh Phúc', 'nhom_3', true),
  ('Quang Khải', 'nhom_2', true),
  ('Quốc Hoàng', 'nhom_3', true),
  ('Hoàng Uyên', 'nhom_3', true),
  ('Gia Huy', 'nhom_1', true),
  ('Quang Huy', 'nhom_2', true),
  ('Thảo Nguyên', 'nhom_1', true),
  ('Đại An', 'nhom_3', true),
  ('Bảo Ngân', 'nhom_1', true),
  ('Bảo Hân', 'nhom_1', true),
  ('Ngọc Quỳnh', 'nhom_2', true),
  ('Tuệ Lâm', 'nhom_2', true),
  ('Tiểu My', 'nhom_1', true),
  ('Minh Thảo', 'nhom_2', true),
  ('Quang Hưng', 'nhom_2', true),
  ('Phương Thy', 'nhom_1', true),
  ('Anh Khôi', 'nhom_3', true),
  ('Lâm Anh', 'nhom_1', true),
  ('Đức Đam', 'nhom_2', true),
  ('Hoàng Anh', 'nhom_2', true),
  ('Trúc Lam', 'nhom_2', true),
  ('Bảo Anh', 'nhom_2', true),
  ('Minh Châu', 'nhom_2', true);
